server:
  port: 8083

spring:
  application:
    name: Payroll-Service
  config:
    import:
    - configserver:http://192.168.1.60:5050
    
logging:
  level:
    root: INFO
  file:
    name: G:\HRMS_API\Payroll\app.log